# -*- coding: utf-8 -*-
"""
Created on Thu Jun  4 22:52:55 2020

@author: sgarg129
"""

import pandas as pd
import datetime as dt
import smtplib
#import email.utils
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.message import EmailMessage
from email.parser import Parser

df_emp_fin = pd.read_csv("C:/work_requests/Hackathon/Employee_Consolidated_data_v1.csv")

df_emp_fin['date_f'] = pd.to_datetime(df_emp_fin.Date, format="%m/%d/%Y").dt.date

df_emp_fin['pulse_diff'] = ((((df_emp_fin['Normal Pulse'] - df_emp_fin['Pulse'])/df_emp_fin['Normal Pulse'])*100).round(0))
df_emp_fin['Diastolic_diff'] = ((((df_emp_fin['Normal Diastolic'] - df_emp_fin['Diastolic'])/df_emp_fin['Normal Diastolic'])*100).round(0))
df_emp_fin['Systolic_diff'] = ((((df_emp_fin['Normal Systolic'] - df_emp_fin['Systolic'])/df_emp_fin['Normal Systolic'])*100).round(0))
df_emp_fin['resp_rate_diff'] = ((((df_emp_fin['Normal Respiration Rate'] - df_emp_fin['Respiration Rate'])/df_emp_fin['Normal Respiration Rate'])*100).round(0))
df_emp_fin['body_temp_diff'] = ((((df_emp_fin['Normal Body Temperature'] - df_emp_fin['Body Temperature'])/df_emp_fin['Normal Body Temperature'])*100).round(0))
df_emp_fin['emp_age'] = ((dt.datetime.now() - pd.to_datetime(df_emp_fin['Employee DOB'], format='%m/%d/%Y')).dt.days / 365.25).round(0)

current_df = df_emp_fin[df_emp_fin.date_f == df_emp_fin.date_f.max()]
current_df.loc[((abs(current_df.pulse_diff) > 10) | 
                (abs(current_df.Diastolic_diff) > 10) |
                (abs(current_df.Systolic_diff) > 10) |
                (abs(current_df.resp_rate_diff) > 10) |
                (abs(current_df.resp_rate_diff) > 10)), 'alert_flag_yn'] = 'Y'


df_send_email = current_df[current_df.alert_flag_yn == 'Y']

def emailNotification(subject, body, mylist):
    headers = Parser().parsestr('From: sonal_garg@optum.com\n'
                                'To: {}\n'
                                
                                'subject: {}\n'
                                'body: {}'.format(mylist,subject,body))
    
    # msg = MIMEMultipart("alternative",None, [MIMEText(headers['body'])])
    msg = EmailMessage() 
    msg['To'] = ",".join(mylist)
    
    msg['From'] = headers['from']
    msg['Subject'] = headers['subject']
    msg.set_content(body)
    server = smtplib.SMTP('mail')
    server.sendmail(headers['from'], msg['To'],msg.as_string())
    server.quit()

body = """\
Hi {manager},

Suraksha360 has raised screening alert for one of your reportee - {emp_name}, Employee ID - {empid}. Employee will be monitored for his Vital symptoms for 7 days and you will be further notified of his health status and Isolation approval if 
Dr.{drname} disapproves his presence in the office premise.

Thanks,
Suraksha360 Team"""

body2 = """\
Hi {manager},

After monitoring the health status of your reportee - {emp_name}, Employee ID - {empid}  generated by Suraksha360  , Dr.{drname} has observed health anomaly and disapproves his presence in the office.
Please take care of the necessary actions required to assist {emp_name} to Isolate him immediately / Stay and Work at Home .

Thanks.
Suraksha360 Team"""

body3 = """\
Hi {emp_name},

You have been identified by suraksha360 and monitored by Dr.{drname} for your vitals and you are requested to stay at home and  get in touch with necessary medical attention .

Thanks.
Suraksha360 Team"""

for eml in df_send_email['EmployeeID'].unique():
    temp = df_send_email[df_send_email['EmployeeID'] == eml]
    print(temp.ManagerName.values[0])
    emailNotification("Screening alert raised from Suraksha360!!!",
                      body.format(manager=temp.ManagerName.values[0],
                                  drname=temp.PCPFNAME.values[0] + " "+ temp.PCPLNAME.values[0],
                                  empid=temp.EmployeeID.values[0],
                                  emp_name=temp['Employee Name'].values[0]),
                      (temp['pcp_email_id '] + ',' + temp['manager_email_id ']).tolist())
                      
    emailNotification("Presence of {emp_name} at the office premise disapproved !!".format(emp_name=temp['Employee Name'].values[0]),
                      body2.format(manager=temp.ManagerName.values[0],
                                  drname=temp.PCPFNAME.values[0] + " "+ temp.PCPLNAME.values[0],
                                  empid=temp.EmployeeID.values[0],
                                  emp_name=temp['Employee Name'].values[0]),
                      (temp['manager_email_id ']).tolist())
                      
    emailNotification("Need Medical Attention - You are adviced to Stay home!!",
                      body3.format(manager=temp.ManagerName.values[0],
                                  drname=temp.PCPFNAME.values[0] + " "+ temp.PCPLNAME.values[0],
                                  empid=temp.EmployeeID.values[0],
                                  emp_name=temp['Employee Name'].values[0]),
                      (temp['manager_email_id ']).tolist()) 